apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:058264360223:certificate/68a5235d-d35d-4ff5-a952-8049aa425bf9"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
spec:
  rules:
    - host: "www.tjdgus.store"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-service-loadbalancer
                port:
                  number: 80
  tls:
    - hosts:
        - "www.tjdgus.store"
      secretName: tls-secret

