apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # NLB를 사용
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # 내부 접근만 가능하게 설정
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

