apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      nodeSelector:
        nodegroup: tomcat
      containers:
      - name: tomcat
        image: 058264360223.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-ecr:63
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: efs-volume
          mountPath: /usr/local/tomcat/webapps/web-data  # EFS가 마운트될 경로
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: efs  # 이미 존재하는 PVC의 이름
